# Generated by Django 5.0.6 on 2024-05-27 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='EducationLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Education Languages',
            },
        ),
        migrations.CreateModel(
            name='EducationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=150)),
                ('year', models.PositiveIntegerField(null=True)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='api.degree')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=150)),
                ('images', models.ImageField(blank=True, null=True, upload_to='university')),
                ('content', models.TextField(null=True)),
                ('vision', models.TextField(null=True)),
                ('mission', models.TextField(null=True)),
                ('faculty_numbers', models.PositiveIntegerField(null=True)),
                ('bachelor_program_numbers', models.PositiveIntegerField(null=True)),
                ('master_program_numbers', models.PositiveIntegerField(null=True)),
                ('phd_program_numbers', models.PositiveIntegerField(null=True)),
                ('student_numbers', models.CharField(max_length=255, null=True)),
                ('alumni_numbers', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('website', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=100, null=True, unique=True)),
                ('education_languages', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='universities', to='api.educationlanguage')),
                ('education_types', models.ManyToManyField(related_name='universities', to='api.educationtype')),
                ('programs', models.ManyToManyField(related_name='universities', to='api.program')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='university', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'ordering': ['university_name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.program')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.university')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramScholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_percentage', models.PositiveIntegerField(null=True)),
                ('scholarship_year', models.PositiveIntegerField(null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_scholarships', to='api.program')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_scholarships', to='api.university')),
            ],
            options={
                'unique_together': {('program', 'university')},
            },
        ),
    ]
