# Generated by Django 4.2.11 on 2024-06-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='education_languages',
        ),
        migrations.AddField(
            model_name='university',
            name='education_languages',
            field=models.ManyToManyField(related_name='universities', to='api.educationlanguage'),
        ),
    ]
