# Generated by Django 4.2.11 on 2024-06-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_university_education_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='roll_number',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
